name: Collect README.md

on:
  schedule:
    - cron: '0 0 * * 0'  # Exécution une fois par semaine
  workflow_dispatch:     # Exécution manuelle

jobs:
  collect-readmes:
    runs-on: ubuntu-latest


    # Assure que le dépôt actuel est vérifié
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      # Configure l'acces a GitHub Actions
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'


      # Liste tous les depots de l'organisation
      - name: List repositories
        run:  repos=$(gh repo list JulienDroulez31 -L 2000 --json name -q '.[].name')
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}


      # Requete API qui recupere les README
      - name: API Call Repo
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/JulienDroulez31/repo1/README.md \


     # Artifact collect
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: README
          path: readmes/*
          retention-days: 90


    # Environnement
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
