name: Collect README.md

on:
  schedule:
    - cron: '0 0 * * 0'  # Exécution une fois par semaine
  workflow_dispatch:     # Exécution manuelle

jobs:
  collect-readmes:
    runs-on: ubuntu-latest

    steps:
      # Assure que le dépôt actuel est vérifié
      - name: Checkout repository
        uses: actions/checkout@v4


      # Configure l'acces a GitHub Actions
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'


      # Liste tous les dépôts de l'organisation
      - name: List repositories
        id: list_repos
        run: |
          gh repo list JulienDroulez31 -L 2000 --json name --jq '.[].name' > repos.txt
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}


      # Crée le dossier readmes et faire des API Calls
      - name: API Call and collect README.md
        run: |
          mkdir -p readmes
          while read repo_name; do
            echo "API Call $repo_name"
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/JulienDroulez31/$repo_name/README.md \
             | jq -r '.content' | base64 --decode > readmes/README-$repo_name.md
          done < repos.txt 


      # Artifact collect
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: README
          path: readmes/*
          retention-days: 90
