name: Collect README.md

on:
  schedule:
    - cron: '0 0 * * 0' # Exécution une fois par semaine
  workflow_dispatch:    # Exécution manuelle

jobs:
  collect-readmes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Assure que le dépôt actuel est vérifié

      - name: Clone repositories
        run: |
          mkdir -p readmes
          
          # Cloner les repositories existants
          git clone https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/JulienDroulez31/repo1.git repo1
          git clone https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/JulienDroulez31/repo2.git repo2

          # Copier les fichiers README.md
          cp repo1/README.md readmes/README-repo1.md
          cp repo2/README.md readmes/README-repo2.md

      - name: Verify Git repository
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the directory:"
          ls -la
          echo "Check for .git directory:"
          if [ -d ".git" ]; then echo ".git directory exists"; else echo ".git directory does not exist"; fi

      - name: Commit and push README.md
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git add readmes/*
          git commit -m "Update README.md files from other repositories" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
