name: Collect README V2.md

on:
  push:
  schedule:
    - cron: '0 0 * * 0'  # Exécution une fois par semaine
  workflow_dispatch:     # Exécution manuelle

jobs:
  collect-readmes:
    runs-on: ubuntu-latest

    steps:
      # Lister les repos et récupérer les README.md
      - name: Collect README.md from repositories
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repos=$(gh repo list JulienDroulez31 -L 2000 --json name --jq '.[].name')
          for repo_name in $repos; do
            echo "Fetching README.md from $repo_name"
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/JulienDroulez31/$repo_name/contents/README.md \
              | jq -r '.content' | base64 --decode > README-$repo_name.md
          done

      # Lister les fichiers pour voir si les README.md ont été récupérés
      - name: Lister les fichiers README.md récupérés
        run: ls -l *.md

      # Installer Node.js et le package markdown-to-json
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Convertir README.md en JSON
        run: |
          env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          repos=$(gh repo list JulienDroulez31 -L 2000 --json name --jq '.[].name')
          npm install @moox/markdown-to-json
          
          for repo_name in $repos; do
            echo "Convert README-$repo_name.md to README-$repo_name.json"
            npx markdown-to-json "README-$repo_name.md" > "README-$repo_name.json"
          done

      # Lister les fichiers JSON après conversion
      - name: Lister les fichiers JSON créés
        run: ls -l *.json

      # Regrouper les fichiers JSON
      - name: Regrouper les fichiers JSON
        run: |
          mkdir -p readmes
          for file in README-*.json; do
            echo "Moving $file to readmes/"
            mv "$file" "readmes/"
          done

      # Upload artifacts
      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: README
          path: readmes
          retention-days: 90
