name: Collect README V2.md

on:
  push:
  schedule:
    - cron: '0 0 * * 0'  # Exécution une fois par semaine
  workflow_dispatch:     # Exécution manuelle

jobs:
  collect-readmes:
    runs-on: ubuntu-latest

    steps:
      # Lister les repos et récupérer les README.md
      - name: Collect README.md from repositories
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repos=$(gh repo list JulienDroulez31 -L 2000 --json name --jq '.[].name')
          for repo_name in $repos; do
            echo "Fetching README.md from $repo_name"
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/JulienDroulez31/$repo_name/contents/README.md \
              | jq -r '.content' | base64 --decode > README-$repo_name.md
          done

      # Lister les fichiers pour voir si les README.md ont été récupérés
      - name: Lister les fichiers README.md récupérés
        run: ls -l

      # Installation de Python et des outils nécessaires
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
           python-version: '3.10'

      # Installation de npm pour utiliser markdown-to-json
      - name: Installer markdown-to-json
        run: npm install @moox/markdown-to-json

      # Convertir les fichiers README.md en JSON
      - name: Convertir README.md en JSON
        run: |
          repos=$(ls README-*.md)
          for repo_file in $repos; do
            echo "Converting $repo_file to JSON"
            markdown-to-json "$repo_file" > ${repo_file%.md}.json
          done

      # Lister les fichiers JSON après conversion
      - name: Lister les fichiers JSON créés
        run: ls -l

      # Regrouper les fichiers JSON dans un dossier
      - name: Regrouper les fichiers JSON
        run: |
           mkdir -p readmes
           mv README-*.json readmes/

      # Upload des fichiers JSON en tant qu'artefacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: README
          path: readmes
          retention-days: 90
