name: Collect README V2.md

on:
  push:
  schedule:
    - cron: '0 0 * * 0'  # Exécution une fois par semaine
  workflow_dispatch:     # Exécution manuelle

jobs:
  collect-readmes:
    runs-on: ubuntu-latest

    steps:

      # Liste tous les dépôts de l'organisation et récupère les README.md
      - name: Collect README.md from repositories
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repos=$(gh repo list JulienDroulez31 -L 2000 --json name --jq '.[].name')
          for repo_name in $repos; do
            echo "Fetching README.md from $repo_name"
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/JulienDroulez31/$repo_name/README.md \
              | jq -r '.content' | base64 --decode > README-$repo_name.md
          done


      # # Installation de python
      # - uses: actions/checkout@v4
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.10' 


      # Lister et convertir fichiers MD en JSON
      - name: Convertir MD en JSON
        run: |
          repos=$(ls | grep README)

          sudo apt-get install pandoc

          for repo_file in $repos; do
            echo "Convert $repo_file to JSON"
            pandoc -f markdown -t json -o $repo_file.json README.md
          done

      # Regrouper les fichiers CSV
      - name: Regrouper les fichiers CSV
        run: |
          repos=$(ls | grep README)
          for repo_name in $repos; do
          echo
          mkdir -p readmes
          cat $repo_name/README.csv > readmes/README-$repo_name.csv

      # Upload artifacts
      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: README
          path: README.md
          retention-days: 90
